import type { Metadata } from "next";
import { Dancing_Script } from "next/font/google";
import "./globals.css";

const valentineFont = Dancing_Script({
  subsets: ["latin"],
  weight: ["400", "700"], // เลือกน้ำหนักตัวอักษร
  variable: "--font-valentine", // ตั้งค่าให้ใช้ใน CSS ได้
});

export const metadata: Metadata = {
  title: "For you!",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${valentineFont.variable} bg-pink-50 text-pink-900`}>
        {children}
      </body>
    </html>
  );
}
